/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 riot_mech_model.glb --transform
Author: SchrisArt (https://sketchfab.com/SchrisArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/riot-mech-model-7b8738c8b0ed4561814856503a4642fb
Title: Riot Mech Model
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { gsap } from "gsap";

export function Riot(props) {
  const { nodes, materials } = useGLTF(
    "./models/riot_mech_model-transformed.glb"
  );

  const mech = useRef();
  const scroll = useScroll();
  const tl = useRef();

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline({
      defaults: { duration: 2, ease: "power1.inOut" },
    });

    tl.current
      .to(mech.current.rotation, { y: -1 }, 2)
      .to(mech.current.position, { x: 1 }, 2)

      .to(mech.current.rotation, { y: 1 }, 6)
      .to(mech.current.position, { x: -1 }, 6)

      .to(mech.current.rotation, { y: 3 }, 11)
      .to(mech.current.rotation, { x: 0 }, 11)
      .to(mech.current.position, { x: 1 }, 11)

      .to(mech.current.rotation, { y: 6 }, 13)
      .to(mech.current.rotation, { x: 0 }, 13)
      .to(mech.current.position, { x: 0 }, 13)

      .to(mech.current.rotation, { y: -1 }, 16)
      .to(mech.current.rotation, { x: 0 }, 16)
      .to(mech.current.position, { x: 0 }, 16)

      .to(mech.current.rotation, { y: 1 }, 20)
      .to(mech.current.rotation, { x: 0 }, 20)
      .to(mech.current.position, { x: 0 }, 20);
  }, []);

  return (
    <group {...props} dispose={null} ref={mech}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.MechModel_BodyUp_0.geometry}
            material={materials.BodyUp}
          />
          {/* <meshPhysicalMaterial
              color="#aaa"
              roughness={0.2}
              metalness={1}
              reflectivity={0.5}
              iridescence={0.3}
              iridescenceIOR={1}
              iridescenceThicknessRange={[100, 1000]}
            /> */}
          <mesh
            geometry={nodes.MechModel_BodyDown_0.geometry}
            material={materials.BodyDown}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/riot_mech_model-transformed.glb");
